version: '3.7'

services:
  database:
    image: postgres
    container_name: database_gcb_test
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=doctors_api
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: gcb_test
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
